# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ad0c0928bf05e0629a760ca0e8c179b51e7049112d4ac361cc48d9e1fca6c321dea24683e15dcc70661fcedb6a9a15c30796d0268eee71600a8941604194380

test:
  secret_key_base: ed07fc610d9fddbf297b75e8407494564a084892e861fc24f06f7664f52ecd422d76991117cd234bb2b663b510aa2acf44526ba5098fd7a82f39239160981fa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
